syntax = "proto3";

package collections_sample_pack;

message ArrayOfArrayOfArrayOfString {
  repeated ArrayOfArrayOfString arrays = 1;
}

message ArrayOfArrayOfString {
  repeated ArrayOfString arrays = 1;
}

message ArrayOfByte {
  repeated uint32 elements = 1;
}

message ArrayOfMultiDimensionalArrayOfByte {
  repeated MultiDimensionalArrayOfByte arrays = 1;
}

message ArrayOfString {
  repeated string elements = 1;
}

message DictionaryOfStringInt32 {
  map<string, int32> mapping = 1;
}

message Item {
  int32 id = 1;
}

message KeyValuePairOfIEnumerableOfItemDictionaryOfStringInt32 {
  repeated Item key = 1;

  map<string, int32> value = 2;
}

message KeyValuePairOfItemInt32 {
  Item key = 1;

  int32 value = 2;
}

message KeyValuePairOfLettersString {
  Letters key = 1;

  string value = 2;
}

message MultiDimensionalArrayOfArrayOfByte {
  repeated ArrayOfByte elements = 1;

  repeated int32 dimensions = 2;
}

message MultiDimensionalArrayOfByte {
  repeated uint32 elements = 1;

  repeated int32 dimensions = 2;
}

message MultiDimensionalArrayOfInt32 {
  repeated int32 elements = 1;

  repeated int32 dimensions = 2;
}

message Order {
  repeated string items = 1;

  repeated KeyValuePairOfItemInt32 item_quantities1 = 2;

  map<string, DictionaryOfStringInt32> item_quantities2 = 3;

  repeated KeyValuePairOfIEnumerableOfItemDictionaryOfStringInt32 item_quantities3 = 4;

  map<uint32, string> item_quantities4 = 5;

  map<uint64, string> item_quantities5 = 6;

  repeated KeyValuePairOfLettersString item_quantities6 = 7;

  ArrayOfArrayOfArrayOfString string_jagged_array = 8;

  MultiDimensionalArrayOfInt32 int_multidimensional_array = 9;

  MultiDimensionalArrayOfArrayOfByte byte_multidimensional_array_of_arrays = 10;

  ArrayOfMultiDimensionalArrayOfByte byte_array_of_multidimensional_arrays = 11;
}

enum Letters {
  LETTERS_A = 0;

  LETTERS_B = 1;
}
